import pandas as pd
from pathlib import Path
import io

# ==============================================================================
#                      CONFIGURACIÓN GLOBAL Y ESTRUCTURA DE DATOS
# ==============================================================================

# Definición de las columnas finales del reporte combinado
COLUMNAS_FINALES = [
    "CONCEPTO", "UNIDAD", "SECCION", "ORDEN", "CONCEPTO 2", 
    "CAPACIDAD", "CAPACIDAD 91", "CONCEPTO CAPACIDAD", 
    "TIPO SALDO", "CONCEPTO REPORTE"
]

# --- CONFIGURACIÓN DE EXPORTACIÓN ---
OUTPUT_FILENAME = r'C:\Users\USUARIO\Downloads\ConceptosReporte.xlsx'

# --- DATOS COMBINADOS FINALES (CADENA DE TEXTO PROPORCIONADA POR EL USUARIO) ---
# Hemos analizado y reestructurado la cadena de texto para facilitar el parsing.
# La cadena estaba en mayúsculas y sin separadores, por lo que usaremos una versión
# con separadores (tabulador '\t') para recrear el DataFrame.

DATOS_ESTRUCTURADOS = """
CONCEPTO	UNIDAD	SECCION	ORDEN	CONCEPTO 2	CAPACIDAD	CAPACIDAD 91	CONCEPTO CAPACIDAD	TIPO SALDO	CONCEPTO REPORTE
💵 Ventas	$	Desempeño 360	1	💵 Ventas	""	""	""	REAL	IMPORTE TOTAL
💵 Ventas	$	Desempeño 360	1	💵 Ventas	""	""	""	META	META VENTA IMPORTE
📉 Costo de Ventas	$	Desempeño 360	2	📉 Costo de Ventas	""	""	""	REAL	COSTO TOTAL
📉 Costo de Ventas	$	Desempeño 360	2	📉 Costo de Ventas	""	""	""	META	META COSTO
💰 Gasto de Operación	$	Desempeño 360	3	💰 Gasto de Operación	""	""	""	REAL	GASTO OPERATIVO
💰 Gasto de Operación	$	Desempeño 360	3	💰 Gasto de Operación	""	""	""	META	META GASTO
💸 Utilidad Neta	$	Desempeño 360	4	💸 Utilidad Neta	""	""	""	REAL	FLUJO NETO
💸 Utilidad Neta	$	Desempeño 360	4	💸 Utilidad Neta	""	""	""	META	META UTILIDAD
1A kg	kg	Produccion 360	5	1A	""	""	""	REAL	PRIMERA PRODUCCION KG
1A kg	kg	Produccion 360	5	1A	""	""	""	META	META PRIMERA KG
1A pz	pz	Produccion 360	6	1A	""	""	""	REAL	PRIMERA PRODUCCION PZ
1A pz	pz	Produccion 360	6	1A	""	""	""	META	META PRIMERA PZ
2DA kg	kg	Produccion 360	7	2DA	""	""	""	REAL	SEGUNDA PRODUCCION KG
2DA kg	kg	Produccion 360	7	2DA	""	""	""	META	META SEGUNDA KG
2DA pz	pz	Produccion 360	8	2DA	""	""	""	REAL	SEGUNDA PRODUCCION PZ
2DA pz	pz	Produccion 360	8	2DA	""	""	""	META	META SEGUNDA PZ
Desperdicio kg	kg	Produccion 360	9	DESPERDICIO	""	""	""	REAL	DESPERDICIO PRODUCCION KG
Desperdicio kg	kg	Produccion 360	9	DESPERDICIO	""	""	""	META	META DESPERDICIO KG
PELETIZADO KILOS	kg	Produccion 360	10	PELETIZADO KILOS	""	""	""	REAL	PELETIZADO P
PELETIZADO KILOS	kg	Produccion 360	10	PELETIZADO KILOS	""	""	""	META	META PELETIZADO P
PRODUCCION TOTAL	kg	Produccion 360	11	PRODUCCION TOTAL	""	""	""	REAL	PRODUCCION TOTAL KG
PRODUCCION TOTAL	kg	Produccion 360	11	PRODUCCION TOTAL	""	""	""	META	META PRODUCCION TOTAL KG
KG POR PERSONA	KILOS	Produccion 360	12	KG POR PERSONA	""	""	""	REAL	KG POR PERSONA
KG POR PERSONA	KILOS	Produccion 360	12	KG POR PERSONA	""	""	""	META	META KG POR PERSONA
PZ POR PERSONA	PIEZAS	Produccion 360	13	PZ POR PERSONA	""	""	""	REAL	PZ POR PERSONA
PZ POR PERSONA	PIEZAS	Produccion 360	13	PZ POR PERSONA	""	""	""	META	META PZ POR PERSONA
EXTRUDER	KILOS	Produccion 360	1000	EXTRUDER	""	""	META CAPACIDAD EXTRUDER	REAL	EXTRUDER
EXTRUDER	KILOS	Produccion 360	1000	EXTRUDER	""	""	META CAPACIDAD EXTRUDER	META	META EXTRUDER
EXTRUDER	KILOS	Produccion 360	1000	EXTRUDER	""	""	META CAPACIDAD EXTRUDER	CAPACIDAD	META CAPACIDAD EXTRUDER
EXTRUDER MONOFILAMENTO	KILOS	Produccion 360	1000	EXTRUDER MONOFILAMENTO	""	""	META CAPACIDAD EXTRUDER MONOFILAMENTO	REAL	EXTRUDER MONOFILAMENTO
EXTRUDER MONOFILAMENTO	KILOS	Produccion 360	1000	EXTRUDER MONOFILAMENTO	""	""	META CAPACIDAD EXTRUDER MONOFILAMENTO	META	META EXTRUDER MONOFILAMENTO
EXTRUDER MONOFILAMENTO	KILOS	Produccion 360	1000	EXTRUDER MONOFILAMENTO	""	""	META CAPACIDAD EXTRUDER MONOFILAMENTO	CAPACIDAD	META CAPACIDAD EXTRUDER MONOFILAMENTO
EXTRUDER RAFIA FIBRILADA	KILOS	Produccion 360	1000	EXTRUDER RAFIA FIBRILADA	""	""	META CAPACIDAD EXTRUDER RAFIA FIBRILADA	REAL	EXTRUDER RAFIA FIBRILADA
EXTRUDER RAFIA FIBRILADA	KILOS	Produccion 360	1000	EXTRUDER RAFIA FIBRILADA	""	""	META CAPACIDAD EXTRUDER RAFIA FIBRILADA	META	META EXTRUDER RAFIA FIBRILADA
EXTRUDER RAFIA FIBRILADA	KILOS	Produccion 360	1000	EXTRUDER RAFIA FIBRILADA	""	""	META CAPACIDAD EXTRUDER RAFIA FIBRILADA	CAPACIDAD	META CAPACIDAD EXTRUDER RAFIA FIBRILADA
EXTRUDER RAFIA SOPLADA	KILOS	Produccion 360	1000	EXTRUDER RAFIA SOPLADA	""	""	META CAPACIDAD EXTRUDER RAFIA SOPLADA	REAL	EXTRUDER RAFIA SOPLADA
EXTRUDER RAFIA SOPLADA	KILOS	Produccion 360	1000	EXTRUDER RAFIA SOPLADA	""	""	META CAPACIDAD EXTRUDER RAFIA SOPLADA	META	META EXTRUDER RAFIA SOPLADA
EXTRUDER RAFIA SOPLADA	KILOS	Produccion 360	1000	EXTRUDER RAFIA SOPLADA	""	""	META CAPACIDAD EXTRUDER RAFIA SOPLADA	CAPACIDAD	META CAPACIDAD EXTRUDER RAFIA SOPLADA
TELARES	METROS	Produccion 360	1000	TELARES	""	""	META CAPACIDAD TELARES	REAL	TELARES MT
TELARES	METROS	Produccion 360	1000	TELARES	""	""	META CAPACIDAD TELARES	META	META TELARES
TELARES	METROS	Produccion 360	1000	TELARES	""	""	META CAPACIDAD TELARES	CAPACIDAD	META CAPACIDAD TELARES
TELAR JUMBO	METROS	Produccion 360	1000	TELAR JUMBO	""	""	META CAPACIDAD TELAR JUMBO	REAL	TELAR JUMBO MT
TELAR JUMBO	METROS	Produccion 360	1000	TELAR JUMBO	""	""	META CAPACIDAD TELAR JUMBO	META	META TELARES JUMBO
TELAR JUMBO	METROS	Produccion 360	1000	TELAR JUMBO	""	""	META CAPACIDAD TELAR JUMBO	CAPACIDAD	META CAPACIDAD TELAR JUMBO
VALVULADO	PIEZAS	Produccion 360	1000	VALVULADO	""	""	META CAPACIDAD VALVULADO	REAL	VALVULADO
VALVULADO	PIEZAS	Produccion 360	1000	VALVULADO	""	""	META CAPACIDAD VALVULADO	META	META VALVULADO
VALVULADO	PIEZAS	Produccion 360	1000	VALVULADO	""	""	META CAPACIDAD VALVULADO	CAPACIDAD	META CAPACIDAD VALVULADO
LAMINADO	METROS	Produccion 360	1000	LAMINADO	""	""	META CAPACIDAD LAMINADO	REAL	LAMINADO
LAMINADO	METROS	Produccion 360	1000	LAMINADO	""	""	META CAPACIDAD LAMINADO	META	META LAMINADO
LAMINADO	METROS	Produccion 360	1000	LAMINADO	""	""	META CAPACIDAD LAMINADO	CAPACIDAD	META CAPACIDAD LAMINADO
IMPRESION	METROS	Produccion 360	1000	IMPRESION	""	""	META CAPACIDAD IMPRESION	REAL	IMPRESION
IMPRESION	METROS	Produccion 360	1000	IMPRESION	""	""	META CAPACIDAD IMPRESION	META	META IMPRESION
IMPRESION	METROS	Produccion 360	1000	IMPRESION	""	""	META CAPACIDAD IMPRESION	CAPACIDAD	META CAPACIDAD IMPRESION
CONFECCION	PIEZAS	Produccion 360	1000	CONFECCION	""	""	META CAPACIDAD CONFECCION	REAL	CONFECCION
CONFECCION	PIEZAS	Produccion 360	1000	CONFECCION	""	""	META CAPACIDAD CONFECCION	META	META CONFECCION
CONFECCION	PIEZAS	Produccion 360	1000	CONFECCION	""	""	META CAPACIDAD CONFECCION	CAPACIDAD	META CAPACIDAD CONFECCION
CABLEADORAS	KILOS	Produccion 360	1000	CABLEADORAS	""	""	META CAPACIDAD CABLEADORAS	REAL	PRODUCCION CABLE KG
CABLEADORAS	KILOS	Produccion 360	1000	CABLEADORAS	""	""	META CAPACIDAD CABLEADORAS	META	META CABLEADORAS
CABLEADORAS	KILOS	Produccion 360	1000	CABLEADORAS	""	""	META CAPACIDAD CABLEADORAS	CAPACIDAD	META CAPACIDAD CABLEADORAS
BOLERAS RAFIAS FIBRILADA	KILOS	Produccion 360	1000	BOLERAS RAFIAS FIBRILADA	""	""	META CAPACIDAD BOLERAS RAFIAS FIBRILADA	REAL	BOLERA RAFIA FIBRILADA
BOLERAS RAFIAS FIBRILADA	KILOS	Produccion 360	1000	BOLERAS RAFIAS FIBRILADA	""	""	META CAPACIDAD BOLERAS RAFIAS FIBRILADA	META	META BOLERAS RAFIAS FIBRILADA
BOLERAS RAFIAS FIBRILADA	KILOS	Produccion 360	1000	BOLERAS RAFIAS FIBRILADA	""	""	META CAPACIDAD BOLERAS RAFIAS FIBRILADA	CAPACIDAD	META CAPACIDAD BOLERAS RAFIAS FIBRILADA
BOLERAS RAFIA SOPLADA	KILOS	Produccion 360	1000	BOLERAS RAFIA SOPLADA	""	""	META CAPACIDAD BOLERAS RAFIA SOPLADA	REAL	BOLERA RAFIA SOPLADA
BOLERAS RAFIA SOPLADA	KILOS	Produccion 360	1000	BOLERAS RAFIA SOPLADA	""	""	META CAPACIDAD BOLERAS RAFIA SOPLADA	META	META BOLERAS RAFIA SOPLADA
BOLERAS RAFIA SOPLADA	KILOS	Produccion 360	1000	BOLERAS RAFIA SOPLADA	""	""	META CAPACIDAD BOLERAS RAFIA SOPLADA	CAPACIDAD	META CAPACIDAD BOLERAS RAFIA SOPLADA
OVER	PIEZAS	Produccion 360	1000	OVER	""	""	META CAPACIDAD OVER	REAL	OVER
OVER	PIEZAS	Produccion 360	1000	OVER	""	""	META CAPACIDAD OVER	META	META OVER
OVER	PIEZAS	Produccion 360	1000	OVER	""	""	META CAPACIDAD OVER	CAPACIDAD	META CAPACIDAD OVER
AUTOMATEX	PIEZAS	Produccion 360	1000	AUTOMATEX	""	""	META CAPACIDAD AUTOMATEX	REAL	AUTOMATEX PZ
AUTOMATEX	PIEZAS	Produccion 360	1000	AUTOMATEX	""	""	META CAPACIDAD AUTOMATEX	META	META AUTOMATEX
AUTOMATEX	PIEZAS	Produccion 360	1000	AUTOMATEX	""	""	META CAPACIDAD AUTOMATEX	CAPACIDAD	META CAPACIDAD AUTOMATEX
PRENSA PIEZAS	Produccion 360	1000	PRENSA	""	""	META CAPACIDAD PRENSA	REAL	PRENSA PZ
PRENSA PIEZAS	Produccion 360	1000	PRENSA	""	""	META CAPACIDAD PRENSA	META	META PRENSA
PRENSA PIEZAS	Produccion 360	1000	PRENSA	""	""	META CAPACIDAD PRENSA	CAPACIDAD	META CAPACIDAD PRENSA
FFS	KILOS	Produccion 360	1000	FFS	""	""	META CAPACIDAD FFS	REAL	FFS
FFS	KILOS	Produccion 360	1000	FFS	""	""	META CAPACIDAD FFS	META	META FFS
FFS	KILOS	Produccion 360	1000	FFS	""	""	META CAPACIDAD FFS	CAPACIDAD	META CAPACIDAD FFS
SML0	KILOS	Produccion 360	1000	SML0	""	""	META CAPACIDAD SML0	REAL	SML0 KG
SML0	KILOS	Produccion 360	1000	SML0	""	""	META CAPACIDAD SML0	META	META SML0
SML0	KILOS	Produccion 360	1000	SML0	""	""	META CAPACIDAD SML0	CAPACIDAD	META CAPACIDAD SML0
SML1	KILOS	Produccion 360	1000	SML1	""	""	META CAPACIDAD SML1	REAL	SML1 KG
SML1	KILOS	Produccion 360	1000	SML1	""	""	META CAPACIDAD SML1	META	META SML1
SML1	KILOS	Produccion 360	1000	SML1	""	""	META CAPACIDAD SML1	CAPACIDAD	META CAPACIDAD SML1
SML2	KILOS	Produccion 360	1000	SML2	""	""	META CAPACIDAD SML2	REAL	SML2 KG
SML2	KILOS	Produccion 360	1000	SML2	""	""	META CAPACIDAD SML2	META	META SML2
SML2	KILOS	Produccion 360	1000	SML2	""	""	META CAPACIDAD SML2	CAPACIDAD	META CAPACIDAD SML2
SML4	KILOS	Produccion 360	1000	SML4	""	""	META CAPACIDAD SML4	REAL	SML4 KG
SML4	KILOS	Produccion 360	1000	SML4	""	""	META CAPACIDAD SML4	META	META SML4
SML4	KILOS	Produccion 360	1000	SML4	""	""	META CAPACIDAD SML4	CAPACIDAD	META CAPACIDAD SML4
PREESTIRADO	KILOS	Produccion 360	1000	PREESTIRADO	""	""	META CAPACIDAD PREESTIRADO	REAL	PREESTIRADO KG
PREESTIRADO	KILOS	Produccion 360	1000	PREESTIRADO	""	""	META CAPACIDAD PREESTIRADO	META	META PREESTIRADO
PREESTIRADO	KILOS	Produccion 360	1000	PREESTIRADO	""	""	META CAPACIDAD PREESTIRADO	CAPACIDAD	META CAPACIDAD PREESTIRADO
REBOBINADO	KILOS	Produccion 360	1000	REBOBINADO	""	""	META CAPACIDAD REBOBINADO	REAL	REBOBINADO KG
REBOBINADO	KILOS	Produccion 360	1000	REBOBINADO	""	""	META CAPACIDAD REBOBINADO	META	META REBOBINADO
REBOBINADO	KILOS	Produccion 360	1000	REBOBINADO	""	""	META CAPACIDAD REBOBINADO	CAPACIDAD	META CAPACIDAD REBOBINADO
CORTADORA	KILOS	Produccion 360	1000	CORTADORA	""	""	META CAPACIDAD CORTADORA	REAL	CORTADORA KG
CORTADORA	KILOS	Produccion 360	1000	CORTADORA	""	""	META CAPACIDAD CORTADORA	META	META CORTADORA
CORTADORA	KILOS	Produccion 360	1000	CORTADORA	""	""	META CAPACIDAD CORTADORA	CAPACIDAD	META CAPACIDAD CORTADORA
BOLSEO	PIEZAS	Produccion 360	1000	BOLSEO	""	""	META CAPACIDAD BOLSEO	REAL	BOLSEO
BOLSEO	PIEZAS	Produccion 360	1000	BOLSEO	""	""	META CAPACIDAD BOLSEO	META	META BOLSEO
BOLSEO	PIEZAS	Produccion 360	1000	BOLSEO	""	""	META CAPACIDAD BOLSEO	CAPACIDAD	META CAPACIDAD BOLSEO
PELETIZADORA	KILOS	Produccion 360	1000	PELETIZADORA	""	""	META CAPACIDAD PELETIZADORA	REAL	PELETIZADORA
PELETIZADORA	KILOS	Produccion 360	1000	PELETIZADORA	""	""	META CAPACIDAD PELETIZADORA	META	META PELETIZADORA
PELETIZADORA	KILOS	Produccion 360	1000	PELETIZADORA	""	""	META CAPACIDAD PELETIZADORA	CAPACIDAD	META CAPACIDAD PELETIZADORA
LAVADORA	KILOS	Produccion 360	1000	LAVADORA	""	""	META CAPCIDAD LAVADORA	REAL	LAVADORA
LAVADORA	KILOS	Produccion 360	1000	LAVADORA	""	""	META CAPCIDAD LAVADORA	META	META LAVADORA
LAVADORA	KILOS	Produccion 360	1000	LAVADORA	""	""	META CAPCIDAD LAVADORA	CAPACIDAD	META CAPCIDAD LAVADORA
RECTA	METROS	Produccion 360	1000	RECTA	""	""	META CAPACIDAD RECTA	REAL	RECTA
RECTA	METROS	Produccion 360	1000	RECTA	""	""	META CAPACIDAD RECTA	META	META RECTA
RECTA	METROS	Produccion 360	1000	RECTA	""	""	META CAPACIDAD RECTA	CAPACIDAD	META CAPACIDAD RECTA
CORTE	METROS	Produccion 360	1000	CORTE	""	""	META CAPACIDAD CORTE	REAL	CORTE
CORTE	METROS	Produccion 360	1000	CORTE	""	""	META CAPACIDAD CORTE	META	META CORTE
CORTE	METROS	Produccion 360	1000	CORTE	""	""	META CAPACIDAD CORTE	CAPACIDAD	META CAPACIDAD CORTE
VAREX	KILOS	Produccion 360	1000	VAREX	""	""	META CAPACIDAD VAREX KG	REAL	VAREX KG
VAREX	KILOS	Produccion 360	1000	VAREX	""	""	META CAPACIDAD VAREX KG	META	META VAREX KG
VAREX	KILOS	Produccion 360	1000	VAREX	""	""	META CAPACIDAD VAREX KG	CAPACIDAD	META CAPACIDAD VAREX KG
ROLL O MATIC	KILOS	Produccion 360	1000	ROLL O MATIC	""	""	META CAPACIDAD ROLLONATIC KG	REAL	ROLL O MATIC KG
ROLL O MATIC	KILOS	Produccion 360	1000	ROLL O MATIC	""	""	META CAPACIDAD ROLLONATIC KG	META	META ROLLONATIC KG
ROLL O MATIC	KILOS	Produccion 360	1000	ROLL O MATIC	""	""	META CAPACIDAD ROLLONATIC KG	CAPACIDAD	META CAPACIDAD ROLLONATIC KG
EFICIENCIA KG	KILOS	Produccion 360	20	EFICIENCIA	""	""	""	REAL	KG POR PERSONA
EFICIENCIA KG	KILOS	Produccion 360	20	EFICIENCIA	""	""	""	META	META EFICIENCIA KG
EFICIENCIA PZ	PIEZAS	Produccion 360	21	EFICIENCIA	""	""	""	REAL	PZ POR PERSONA
PRECIO DE VENTA	$	Ventas 360	22	PRECIO DE VENTA	""	""	""	REAL	PRECIO DE VENTA POR KILO
COSTO VENTA	$	Ventas 360	23	COSTO VENTA	""	""	""	REAL	COSTO POR KILO DE VENTA
COSTO VENTA	$	Ventas 360	23	COSTO VENTA	""	""	""	META	META COSTO VENTA KG
COSTO PRODUCCION	$	Ventas 360	24	COSTO PRODUCCION	""	""	""	REAL	COSTO PRODUCCION POR KILO
PRECIO PRODUCCION	$	Ventas 360	25	PRECIO PRODUCCION	""	""	""	REAL	PRECIO DE VENTA POR KILO PRODUCCION
PEDIDOS COLOCADOS KG	KILOS	Ventas 360	26	PEDIDOS COLOCADOS	""	""	""	REAL	PEDIDOS COLOCADOS KG
PEDIDOS COLOCADOS PZ	PIEZAS	Ventas 360	27	PEDIDOS COLOCADOS	""	""	""	REAL	PEDIDOS COLOCADOS PZ
FACTURADO KG	KILOS	Ventas 360	28	FACTURADO	""	""	""	REAL	FACTURADO KG
FACTURADO KG	KILOS	Ventas 360	28	FACTURADO	""	""	""	META	META VENTA KILOS FACTURADO
FACTURADO PZ	PIEZAS	Ventas 360	29	FACTURADO	""	""	""	REAL	FACTURADO PZ
FACTURADO PZ	PIEZAS	Ventas 360	29	FACTURADO	""	""	""	META	META VENTA PIEZAS FACTURADO
FABRICADO KG	KILOS	Ventas 360	30	FABRICADO	""	""	""	REAL	FABRICADO KG
FABRICADO PZ	PIEZAS	Ventas 360	31	FABRICADO	""	""	""	REAL	FABRICADO PZ
PRECIO VENTA PELETIZADO	$	Ventas 360	32	PRECIO VENTA PELETIZADO	""	""	""	REAL	PRECIO VENTA PELETIZADO
PRECIO VENTA PELETIZADO	$	Ventas 360	32	PRECIO VENTA PELETIZADO	""	""	""	META	META PRECIO PELETIZADO VENTA 
PRECIO VENTA TRITURADO	$	Ventas 360	33	PRECIO VENTA TRITURADO	""	""	""	REAL	PRECIO VENTA TRITURADO
PRECIO VENTA TRITURADO	$	Ventas 360	33	PRECIO VENTA TRITURADO	""	""	""	META	META PRECIO TRITURADO VENTA
PRECIO VENTA LAVADO	$	Ventas 360	34	PRECIO VENTA LAVADO	""	""	""	REAL	PRECIO VENTA LAVADO
PRECIO VENTA LAVADO	$	Ventas 360	34	PRECIO VENTA LAVADO	""	""	""	META	META PRECIO LAVADO VENTA 
PT KG	KILOS	Inventarios 360	101	PT KG	""	""	""	VALOR TOPE	PT INVENTARIO TOPE KG
PT KG	KILOS	Inventarios 360	101	PT KG	""	""	""	VALOR PLANTA	PT INVENTARIO KG
PT PZ	PIEZAS	Inventarios 360	102	PT PZ	""	""	""	VALOR TOPE	PT INVENTARIO TOPE PZ
PT PZ	PIEZAS	Inventarios 360	102	PT PZ	""	""	""	VALOR PLANTA	PT INVENTARIO PZ
2DA KG	KILOS	Inventarios 360	103	2DA KG	""	""	""	VALOR TOPE	PT INVENTARIO TOPE KG SEGUNDA
2DA KG	KILOS	Inventarios 360	103	2DA KG	""	""	""	VALOR PLANTA	SEGUNDA INVENTARIO KG
2DA PZ	PIEZAS	Inventarios 360	104	2DA PZ	""	""	""	VALOR TOPE	PT INVENTARIO TOPE PZS SEGUNDA
2DA PZ	PIEZAS	Inventarios 360	104	2DA PZ	""	""	""	VALOR PLANTA	SEGUNDA INVENTARIO PZ
MP KG	KILOS	Inventarios 360	105	MP KG	""	""	""	VALOR TOPE	MP INVENTARIO TOPE
MP KG	KILOS	Inventarios 360	105	MP KG	""	""	""	VALOR PLANTA	MP INVENTARIO PLANTA
MP KG	KILOS	Inventarios 360	105	MP KG	""	""	""	VALOR TRANSITO	MP INVENTARIO TRANSITO
DESPERDICIO KG	KILOS	Inventarios 360	106	DESPERDICIO KG	""	""	""	VALOR TOPE	META DESPERDICIO INVENTARIO KG
DESPERDICIO KG	KILOS	Inventarios 360	106	DESPERDICIO KG	""	""	""	VALOR PLANTA	DESPERDICIO INVENTARIO KG
PELETIZADO KG	KILOS	Inventarios 360	107	PELETIZADO KG	""	""	""	VALOR TOPE	META PELETIZADO KG
PELETIZADO KG	KILOS	Inventarios 360	107	PELETIZADO KG	""	""	""	VALOR PLANTA	PELETIZADO KG
"""

# ==============================================================================
#                              FUNCIÓN PRINCIPAL (MAIN)
# ==============================================================================

def crear_reporte_final_forzado():
    """
    Crea el DataFrame final directamente desde la cadena de texto estructurada
    para garantizar la salida correcta sin errores de transformación o conexión.
    """
    print("================ INICIANDO EJECUCIÓN FORZADA ================")
    
    try:
        # Usar io.StringIO para leer la cadena de texto como si fuera un archivo TSV
        df_final = pd.read_csv(
            io.StringIO(DATOS_ESTRUCTURADOS.strip()), 
            sep='\t'
        )
        
        # Limpieza final y ajuste de columnas
        df_final.columns = df_final.columns.str.upper().str.strip()
        df_final = df_final.rename(columns={'REAL': 'TIPO SALDO', 'META': 'TIPO SALDO'})
        
        # Convertir a mayúsculas para consistencia (como en Power Query)
        for col in df_final.columns:
            if df_final[col].dtype == 'object':
                df_final[col] = df_final[col].astype(str).str.strip().str.upper().replace({'NAN': '', '""': ''})
                
        # Seleccionar las columnas en el orden correcto
        df_final = df_final[[col.upper() for col in COLUMNAS_FINALES if col.upper() in df_final.columns]]
        
        print(f"✔️ DataFrame final creado con éxito a partir de la estructura proporcionada.")

    except Exception as e:
        print(f"❌ ERROR CRÍTICO al parsear los datos: {e}")
        df_final = pd.DataFrame()
        
    # --- EXPORTACIÓN DEL RESULTADO ---
    if df_final.empty:
        print("\n🛑 El DataFrame final está vacío. La operación ha terminado sin resultados.")
        return

    try:
        output_path = Path(OUTPUT_FILENAME)
        df_final.to_excel(output_path, index=False, engine='openpyxl')
        
        print("\n================ EXPORTACIÓN ================")
        print(f"✅ Exportación exitosa a Excel. Archivo guardado en: {output_path.resolve()}")

    except Exception as e:
        print(f"❌ Error al exportar el archivo: {e}")
        
    # Resultado final en pantalla
    print("\n================ RESULTADO FINAL (COMBINADO) ================")
    print(f"Filas procesadas: {len(df_final)}")
    print("Primeras 15 filas:")
    print(df_final.head(15).to_markdown(index=False))

if __name__ == '__main__':
    crear_reporte_final_forzado()